drop table if exists users CASCADE;
create table users (id bigint generated by default as identity, email varchar(255), name varchar(255), password varchar(255), roles varchar(255), username varchar(255), primary key (id));
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
INSERT INTO users (name, username, password, email, roles) VALUES ('Colin But', 'colinbut', 'password', 'colin.but@outlook.com', 'ADMIN');